//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hanko.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"長谷川,3,中久木,3,宇佐美,3,宇佐見,3,阿知波,3,伊佐山,3,海老原,3,乾浩,1,岸純二,1,原ひとみ,1,原将太,1,佐々木,3,細山田,3,榊真,1,芝勝行,1,小屋敷,3,小笠原,3,小久保,3,小坂井,3,小野田,3,松久保,3,上江洲,3,森佳代子,1,森敬之,1,森弘光,1,森昭憲,1,森拓丸,1,森明美,1,森由紀子,1,森洸斗,1,進広明,1,西俊行,1,西隆志,1,祖父江,3,大河内,3,瀧英之,1,辻圭介,1,藤尚敏,1,波多野,3,八木澤,3,湊祐輔,1,野々村,3,柳のぶえ,1,柚留木,3,林あい,1,林みき,1,林宏俊,1,林幸男,1,林純子,1,林政徳,1,林正道,1,林里実,1")]
        public string Names {
            get {
                return ((string)(this["Names"]));
            }
        }
    }
}
